services:
  mysql:
    image: mysql:latest
    container_name: mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=guest
      - MYSQL_DATABASE=stockbroker
    healthcheck:
      test: mysqladmin ping -h localhost --user root --password=guest
      timeout: 5s
      retries: 10
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb: