services:
  mysql:
    image: mysql:latest
    container_name: mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=guest
      - MYSQL_DATABASE=stockbroker
    healthcheck:
      test: mysqladmin ping -h localhost --user root --password=guest
      timeout: 5s
      retries: 10
    volumes:
      - mysqldb:/var/lib/mysql
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - DATABASE_NAME=stockbroker
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=guest
    depends_on:
      mysql:
        condition: service_healthy
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    environment:
      - BACHEND_SERVICE=backend:8080
    depends_on:
      - backend

volumes:
  mysqldb: